LDAP-321: ContextSourceTransactionManager overrides isExistingTransaction
PreviouslyIllegalStateException: No value for key PoolingContextSource
would be thrown.

This is now fixed since isExistingTransaction is now provided.